export enum IncidentStatus {
  REPORTED = 'REPORTED',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RESOLVED = 'RESOLVED',
  DUPLICATE = 'DUPLICATE',
  CANCELED = 'CANCELED'
}
