spring:
  application:
    name: auth-service

server:
  port: 8083

jwt:
  secret: "tajna12345tajna12345tajna12345tajna12345tajna12345tajna12345tajna12345tajna12345"
  expiration: 86400000

user-service:
  url: http://localhost:8082
