server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: incident-service
          uri: http://incident-service:8081
          predicates:
            - Path=/api/incidents/**

        - id: incident-uploads
          uri: http://incident-service:8081
          predicates:
            - Path=/uploads/**

        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/api/users/**

        - id: auth-service
          uri: http://auth-service:8083
          predicates:
            - Path=/api/auth/**

        - id: analytics-service
          uri: http://analytics-service:8084
          predicates:
            - Path=/api/analytics/**

        - id: alert-service
          uri: http://alert-service:8085
          predicates:
            - Path=/api/alerts/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true