server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alert_db
    username: root
    password: rootstudent123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  web:
    resources:
      static-locations: classpath:/static/,file:uploads/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true