server:
  port: 8084

spring:
  application:
    name: analytics-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true