spring:
  application:
    name: incident-service

  datasource:
    url: jdbc:mysql://localhost:3306/incident_db
    username: root
    password: rootstudent123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  web:
    resources:
      static-locations: classpath:/static/,file:uploads/

server:
  port: 8081
